# Generated by Django 3.2.4 on 2021-07-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=90)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
